//
// V1ExportLogsServiceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	struct V1ExportLogsServiceRequest: Codable, Equatable {
		/** An array of ResourceLogs. For data coming from a single resource this array will typically contain one element. Intermediary nodes (such as OpenTelemetry Collector) that receive data from multiple origins typically batch the data before forwarding further and in that case this array will contain multiple elements. */
		internal let resourceLogs: [V1ResourceLogs]?

		internal init(resourceLogs: [V1ResourceLogs]?) {
			self.resourceLogs = resourceLogs
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case resourceLogs = "resource_logs"
		}
	}
}
