//
// V1ResourceLogs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** A collection of InstrumentationLibraryLogs from a Resource. */
	struct V1ResourceLogs: Codable, Equatable {
		internal let resource: V1Resource?
		/** A list of InstrumentationLibraryLogs that originate from a resource. */
		internal let instrumentationLibraryLogs: [V1InstrumentationLibraryLogs]?
		/** This schema_url applies to the data in the \"resource\" field. It does not apply to the data in the \"instrumentation_library_logs\" field which have their own schema_url field. */
		internal let schemaUrl: String?

		internal init(resource: V1Resource?, instrumentationLibraryLogs: [V1InstrumentationLibraryLogs]?, schemaUrl: String?) {
			self.resource = resource
			self.instrumentationLibraryLogs = instrumentationLibraryLogs
			self.schemaUrl = schemaUrl
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case resource
			case instrumentationLibraryLogs = "instrumentation_library_logs"
			case schemaUrl = "schema_url"
		}
	}
}
