//
// V1SeverityNumber.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** Possible values for LogRecord.SeverityNumber.   - SEVERITY_NUMBER_UNSPECIFIED: UNSPECIFIED is the default SeverityNumber, it MUST NOT be used. */
	enum V1SeverityNumber: String, Codable, CaseIterable {
		case unspecified = "SEVERITY_NUMBER_UNSPECIFIED"
		case trace = "SEVERITY_NUMBER_TRACE"
		case trace2 = "SEVERITY_NUMBER_TRACE2"
		case trace3 = "SEVERITY_NUMBER_TRACE3"
		case trace4 = "SEVERITY_NUMBER_TRACE4"
		case debug = "SEVERITY_NUMBER_DEBUG"
		case debug2 = "SEVERITY_NUMBER_DEBUG2"
		case debug3 = "SEVERITY_NUMBER_DEBUG3"
		case debug4 = "SEVERITY_NUMBER_DEBUG4"
		case info = "SEVERITY_NUMBER_INFO"
		case info2 = "SEVERITY_NUMBER_INFO2"
		case info3 = "SEVERITY_NUMBER_INFO3"
		case info4 = "SEVERITY_NUMBER_INFO4"
		case warn = "SEVERITY_NUMBER_WARN"
		case warn2 = "SEVERITY_NUMBER_WARN2"
		case warn3 = "SEVERITY_NUMBER_WARN3"
		case warn4 = "SEVERITY_NUMBER_WARN4"
		case error = "SEVERITY_NUMBER_ERROR"
		case error2 = "SEVERITY_NUMBER_ERROR2"
		case error3 = "SEVERITY_NUMBER_ERROR3"
		case error4 = "SEVERITY_NUMBER_ERROR4"
		case fatal = "SEVERITY_NUMBER_FATAL"
		case fatal2 = "SEVERITY_NUMBER_FATAL2"
		case fatal3 = "SEVERITY_NUMBER_FATAL3"
		case fatal4 = "SEVERITY_NUMBER_FATAL4"
	}
}
