//
// V1ExportMetricsServiceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	struct V1ExportMetricsServiceRequest: Codable, Equatable {
		/** An array of ResourceMetrics. For data coming from a single resource this array will typically contain one element. Intermediary nodes (such as OpenTelemetry Collector) that receive data from multiple origins typically batch the data before forwarding further and in that case this array will contain multiple elements. */
		internal let resourceMetrics: [V1ResourceMetrics]?

		internal init(resourceMetrics: [V1ResourceMetrics]?) {
			self.resourceMetrics = resourceMetrics
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case resourceMetrics = "resource_metrics"
		}
	}
}
