//
// V1ExponentialHistogram.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** ExponentialHistogram represents the type of a metric that is calculated by aggregating as a ExponentialHistogram of all reported double measurements over a time interval. */
	struct V1ExponentialHistogram: Codable, Equatable {
		internal let dataPoints: [V1ExponentialHistogramDataPoint]?
		internal let aggregationTemporality: V1AggregationTemporality?

		internal init(dataPoints: [V1ExponentialHistogramDataPoint]?, aggregationTemporality: V1AggregationTemporality?) {
			self.dataPoints = dataPoints
			self.aggregationTemporality = aggregationTemporality
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case dataPoints = "data_points"
			case aggregationTemporality = "aggregation_temporality"
		}
	}
}
