//
// V1ExponentialHistogramDataPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** ExponentialHistogramDataPoint is a single data point in a timeseries that describes the time-varying values of a ExponentialHistogram of double values. A ExponentialHistogram contains summary statistics for a population of values, it may optionally contain the distribution of those values across a set of buckets. */
	struct V1ExponentialHistogramDataPoint: Codable, Equatable {
		/** The set of key/value pairs that uniquely identify the timeseries from where this point belongs. The list may be empty (may contain 0 elements). */
		internal let attributes: [V1KeyValue]?
		/** StartTimeUnixNano is optional but strongly encouraged, see the the detailed comments above Metric.  Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970. */
		internal let startTimeUnixNano: String?
		/** TimeUnixNano is required, see the detailed comments above Metric.  Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970. */
		internal let timeUnixNano: String?
		/** count is the number of values in the population. Must be non-negative. This value must be equal to the sum of the \"bucket_counts\" values in the positive and negative Buckets plus the \"zero_count\" field. */
		internal let count: String?
		/** sum of the values in the population. If count is zero then this field must be zero.  Note: Sum should only be filled out when measuring non-negative discrete events, and is assumed to be monotonic over the values of these events. Negative events *can* be recorded, but sum should not be filled out when doing so.  This is specifically to enforce compatibility w/ OpenMetrics, see: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#histogram */
		internal let sum: Double?
		/** base = (2^(2^-scale))  The histogram bucket identified by `index`, a signed integer, contains values that are greater than or equal to (base^index) and less than (base^(index+1)).  The positive and negative ranges of the histogram are expressed separately.  Negative values are mapped by their absolute value into the negative range using the same scale as the positive range.  scale is not restricted by the protocol, as the permissible values depend on the range of the data. */
		internal let scale: Int?
		/** zero_count is the count of values that are either exactly zero or within the region considered zero by the instrumentation at the tolerated degree of precision.  This bucket stores values that cannot be expressed using the standard exponential formula as well as values that have been rounded to zero.  Implementations MAY consider the zero bucket to have probability mass equal to (zero_count / count). */
		internal let zeroCount: String?
		internal let positive: ExponentialHistogramDataPointBuckets?
		internal let negative: ExponentialHistogramDataPointBuckets?
		/** Flags that apply to this specific data point.  See DataPointFlags for the available flags and their meaning. */
		internal let flags: Int64?
		internal let exemplars: [V1Exemplar]?

		internal init(attributes: [V1KeyValue]?, startTimeUnixNano: String?, timeUnixNano: String?, count: String?, sum: Double?, scale: Int?, zeroCount: String?, positive: ExponentialHistogramDataPointBuckets?, negative: ExponentialHistogramDataPointBuckets?, flags: Int64?, exemplars: [V1Exemplar]?) {
			self.attributes = attributes
			self.startTimeUnixNano = startTimeUnixNano
			self.timeUnixNano = timeUnixNano
			self.count = count
			self.sum = sum
			self.scale = scale
			self.zeroCount = zeroCount
			self.positive = positive
			self.negative = negative
			self.flags = flags
			self.exemplars = exemplars
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case attributes
			case startTimeUnixNano = "start_time_unix_nano"
			case timeUnixNano = "time_unix_nano"
			case count
			case sum
			case scale
			case zeroCount = "zero_count"
			case positive
			case negative
			case flags
			case exemplars
		}
	}
}
