//
// V1Gauge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** Gauge represents the type of a scalar metric that always exports the \"current value\" for every data point. It should be used for an \"unknown\" aggregation.  A Gauge does not support different aggregation temporalities. Given the aggregation is unknown, points cannot be combined using the same aggregation, regardless of aggregation temporalities. Therefore, AggregationTemporality is not included. Consequently, this also means \"StartTimeUnixNano\" is ignored for all data points. */
	struct V1Gauge: Codable, Equatable {
		internal let dataPoints: [V1NumberDataPoint]?

		internal init(dataPoints: [V1NumberDataPoint]?) {
			self.dataPoints = dataPoints
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case dataPoints = "data_points"
		}
	}
}
