//
// V1Histogram.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** Histogram represents the type of a metric that is calculated by aggregating as a Histogram of all reported measurements over a time interval. */
	struct V1Histogram: Codable, Equatable {
		internal let dataPoints: [V1HistogramDataPoint]?
		internal let aggregationTemporality: V1AggregationTemporality?

		internal init(dataPoints: [V1HistogramDataPoint]?, aggregationTemporality: V1AggregationTemporality?) {
			self.dataPoints = dataPoints
			self.aggregationTemporality = aggregationTemporality
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case dataPoints = "data_points"
			case aggregationTemporality = "aggregation_temporality"
		}
	}
}
