//
// V1InstrumentationLibraryMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** A collection of Metrics produced by an InstrumentationLibrary. */
	struct V1InstrumentationLibraryMetrics: Codable, Equatable {
		internal let instrumentationLibrary: V1InstrumentationLibrary?
		/** A list of metrics that originate from an instrumentation library. */
		internal let metrics: [V1Metric]?
		/** This schema_url applies to all metrics in the \"metrics\" field. */
		internal let schemaUrl: String?

		internal init(instrumentationLibrary: V1InstrumentationLibrary?, metrics: [V1Metric]?, schemaUrl: String?) {
			self.instrumentationLibrary = instrumentationLibrary
			self.metrics = metrics
			self.schemaUrl = schemaUrl
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case instrumentationLibrary = "instrumentation_library"
			case metrics
			case schemaUrl = "schema_url"
		}
	}
}
