//
// V1StringKeyValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** StringKeyValue is a pair of key/value strings. This is the simpler (and faster) version of KeyValue that only supports string values. */
	struct V1StringKeyValue: Codable, Equatable {
		internal let key: String?
		internal let value: String?

		internal init(key: String?, value: String?) {
			self.key = key
			self.value = value
		}
	}
}
