//
// V1Summary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** Summary metric data are used to convey quantile summaries, a Prometheus (see: https://prometheus.io/docs/concepts/metric_types/#summary) and OpenMetrics (see: https://github.com/OpenObservability/OpenMetrics/blob/4dbf6075567ab43296eed941037c12951faafb92/protos/prometheus.proto#L45) data type. These data points cannot always be merged in a meaningful way. While they can be useful in some applications, histogram data points are recommended for new applications. */
	struct V1Summary: Codable, Equatable {
		internal let dataPoints: [V1SummaryDataPoint]?

		internal init(dataPoints: [V1SummaryDataPoint]?) {
			self.dataPoints = dataPoints
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case dataPoints = "data_points"
		}
	}
}
