//
// ProtobufAny.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	struct ProtobufAny: Codable, Equatable {
		internal let typeUrl: String?
		internal let value: Data?

		internal init(typeUrl: String?, value: Data?) {
			self.typeUrl = typeUrl
			self.value = value
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case typeUrl = "type_url"
			case value
		}
	}
}
