//
// RuntimeError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	struct RuntimeError: Codable, Equatable {
		internal let error: String?
		internal let code: Int?
		internal let message: String?
		internal let details: [ProtobufAny]?

		internal init(error: String?, code: Int?, message: String?, details: [ProtobufAny]?) {
			self.error = error
			self.code = code
			self.message = message
			self.details = details
		}
	}
}
