//
// V1KeyValueList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** KeyValueList is a list of KeyValue messages. We need KeyValueList as a message since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches are semantically equivalent. */
	struct V1KeyValueList: Codable, Equatable {
		/** A collection of key/value pairs of key-value pairs. The list may be empty (may contain 0 elements). */
		internal let values: [V1KeyValue]?

		internal init(values: [V1KeyValue]?) {
			self.values = values
		}
	}
}
