//
// V1KeyValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** KeyValue is a key-value pair that is used to store Span attributes, Link attributes, etc. */
	struct V1KeyValue: Codable, Equatable {
		internal let key: String?
		internal let value: V1AnyValue?

		internal init(key: String?, value: V1AnyValue?) {
			self.key = key
			self.value = value
		}
	}
}
