//
// SpanEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** Event is a time-stamped annotation of the span, consisting of user-supplied text description and key-value pairs. */
	struct SpanEvent: Codable, Equatable {
		/** time_unix_nano is the time the event occurred. */
		internal let timeUnixNano: String?
		/** name of the event. This field is semantically required to be set to non-empty string. */
		internal let name: String?
		/** attributes is a collection of attribute key/value pairs on the event. */
		internal let attributes: [V1KeyValue]?
		/** dropped_attributes_count is the number of dropped attributes. If the value is 0, then no attributes were dropped. */
		internal let droppedAttributesCount: Int64?

		internal init(timeUnixNano: String?, name: String?, attributes: [V1KeyValue]?, droppedAttributesCount: Int64?) {
			self.timeUnixNano = timeUnixNano
			self.name = name
			self.attributes = attributes
			self.droppedAttributesCount = droppedAttributesCount
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case timeUnixNano = "time_unix_nano"
			case name
			case attributes
			case droppedAttributesCount = "dropped_attributes_count"
		}
	}
}
