//
// StatusStatusCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	/** - STATUS_CODE_UNSET: The default status.  - STATUS_CODE_OK: The Span has been validated by an Application developers or Operator to have completed successfully.  - STATUS_CODE_ERROR: The Span contains an error. */
		
	enum StatusStatusCode: String, Codable, CaseIterable {
		case unset = "STATUS_CODE_UNSET"
		case ok = "STATUS_CODE_OK"
		case error = "STATUS_CODE_ERROR"
	}
}
