//
// V1ExportTraceServiceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension OTLP {
	struct V1ExportTraceServiceRequest: Codable, Equatable {
		/** An array of ResourceSpans. For data coming from a single resource this array will typically contain one element. Intermediary nodes (such as OpenTelemetry Collector) that receive data from multiple origins typically batch the data before forwarding further and in that case this array will contain multiple elements. */
		internal let resourceSpans: [V1ResourceSpans]?

		internal init(resourceSpans: [V1ResourceSpans]?) {
			self.resourceSpans = resourceSpans
		}

		internal enum CodingKeys: String, CodingKey, CaseIterable {
			case resourceSpans = "resource_spans"
		}
	}
}
