name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    strategy:
      matrix:
        xcodebuild-destination: ['platform=iOS,name=iPhone 13', 'platform=macOS']
        xcodebuild-command: ['build', 'test']

    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests for the matrix
      run: xcodebuild ${{ matrix.xcodebuild-command }} -scheme NautilusTelemetry -destination "${{ matrix.xcodebuild-destination }}"
